// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	chat "github.com/vetal4ik10/lets-go-chat/internal/chat"

	onetimetoken "github.com/vetal4ik10/lets-go-chat/pkdg/onetimetoken"

	websocket "github.com/gorilla/websocket"
)

// ChatClient is an autogenerated mock type for the ChatClient type
type ChatClient struct {
	mock.Mock
}

// Close provides a mock function with given fields:
func (_m *ChatClient) Close() {
	_m.Called()
}

// GetConnection provides a mock function with given fields:
func (_m *ChatClient) GetConnection() *websocket.Conn {
	ret := _m.Called()

	var r0 *websocket.Conn
	if rf, ok := ret.Get(0).(func() *websocket.Conn); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*websocket.Conn)
		}
	}

	return r0
}

// Reader provides a mock function with given fields: s
func (_m *ChatClient) Reader(s chat.ChatServerInterface) {
	_m.Called(s)
}

// getToken provides a mock function with given fields:
func (_m *ChatClient) getToken() onetimetoken.Token {
	ret := _m.Called()

	var r0 onetimetoken.Token
	if rf, ok := ret.Get(0).(func() onetimetoken.Token); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(onetimetoken.Token)
		}
	}

	return r0
}
